version: '2'

services:
  app:
    build:
      # http://stackoverflow.com/questions/27068596/how-to-include-files-outside-of-dockers-build-context
      context: .
      dockerfile: ./env/app/Dockerfile
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - .:/app
    links:
      - db
    command: node src/server/index.js

  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
      MYSQL_DATABASE: sample
