version: '2'

services:
  app:
    build: ./env/app/.
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - .:/app
    links:
      - db
    command: node server.js

  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
      MYSQL_DATABASE: sample
